services:
  # El servidor MQTT (Mosquitto)
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-server
    ports:
      - "1883:1883" # Puerto estándar MQTT
      - "9001:9001" # Puerto para WebSockets (útil para dashboards web)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  # El motor de lógica y Dashboard (Node-RED)
  node-red:
    image: nodered/node-red:latest
    container_name: nodered-logic
    depends_on:
      - mqtt-broker
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    environment:
      - TZ=Europe/Madrid
    privileged: true
    restart: unless-stopped